swagger: "2.0"
info:
  version: "0.0.1"
  title: mean-swagger
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users/create:
    x-swagger-router-controller: users
    post:
      tags:
      - Users
      description: 'Create a single user record.'
      parameters:
      - name: data
        in: body
        description: User Data
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/:
    x-swagger-router-controller: users
    get:
      operationId: getAll
      tags:
      - Users
      description: 'Return all user records.'
      responses:
        "200":
          description: Success
          schema:
            type: 'array'
            items:
              type: object
              allOf:
                - $ref: '#/definitions/User'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}:
    x-swagger-router-controller: users
    get:
      tags:
      - Users
      description: 'Returns a single user record.'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User:
    type: 'object'
    properties:
      _id:
        type: 'string'
        readOnly: true
      name:
        type: 'string'
      email:
        type: 'string'
      password:
        type: 'string'
        
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
